#'原名' = [ '译名', 出现次数 ]

"恭介" = ["恭介", 7803]
"クレア" = ["克蕾亚", 2621]
"桜子" = ["樱子", 2451]
"夏姫" = ["夏姬", 2251]
"志乃" = ["志乃", 1909]
"リサ" = ["莉莎", 1794]
"まゆ" = ["真由", 967]
"一馬" = ["一马", 407]
"高虎" = ["高虎", 169]
"伊藤社長" = ["伊藤社长", 151]
"五十六" = ["五十六", 82]
"藤兵衛" = ["藤兵卫", 74]
"レポーター" = ["记者", 62]
"幸子" = ["幸子", 57]
"魚辰" = ["鱼辰", 27]
"女性客１" = ["女客１", 26]
"女性客２" = ["女客２", 25]
"客１" = ["客人１", 24]
"客２" = ["客人２", 23]
"おっさん１" = ["大叔１", 21]
"常連客" = ["常客", 20]
"ディレクター" = ["导演", 18]
"老婦人" = ["老妇人", 18]
"老人" = ["老人", 18]
"おっさん２" = ["大叔２", 17]
"盗撮男" = ["偷拍男", 14]
"主婦１" = ["主妇１", 13]
"豆田" = ["豆田", 13]
"小笠原・父" = ["小笠原・父", 11]
"おっさん" = ["大叔", 11]
"？？？" = ["？？？", 10]
"おっさん３" = ["大叔３", 9]
"香月・父" = ["香月・父", 8]
"客３" = ["客人３", 8]
"海水浴客１" = ["海水浴客１", 7]
"海水浴客２" = ["海水浴客２", 7]
"お姉さん" = ["大姐姐", 7]
"同級生１" = ["同班同学１", 7]
"同級生２" = ["同班同学２", 7]
"おっさん４" = ["大叔４", 6]
"ナンパ１" = ["搭讪男１", 6]
"香月・母" = ["香月・母", 6]
"課長代理" = ["课长代理", 6]
"志乃の後輩３" = ["志乃的后辈３", 5]
"志乃の後輩１" = ["志乃的后辈１", 5]
"志乃の後輩２" = ["志乃的后辈２", 5]
"バロン中尉" = ["巴隆中尉", 5]
"小笠原・母" = ["小笠原・母", 5]
"海水浴客３" = ["海水浴客３", 5]
"ナンパ２" = ["搭讪男２", 5]
"同級生３" = ["同班同学３", 5]
"ナンパ３" = ["搭讪男３", 5]
"客４" = ["客人４", 5]
"全員" = ["全员", 5]
"客" = ["客人", 5]
"桜子・夏姫・クレア" = ["樱子・夏姬・克蕾亚", 4]
"志乃の後輩４" = ["志乃的后辈４", 4]
"海水浴客４" = ["海水浴客４", 4]
"ナンパ４" = ["搭讪男４", 4]
"若い男１" = ["年轻男子１", 4]
"同級生４" = ["同班同学４", 4]
"豆腐屋" = ["豆腐店", 4]
"部長" = ["部长", 4]
"海水浴客６" = ["海水浴客６", 3]
"若い男２" = ["年轻男子２", 3]
"同級生５" = ["同班同学５", 3]
"電話の声" = ["电话的声音", 3]
"男の声" = ["男人的声音", 3]
"みんな" = ["大家", 3]
"中尉" = ["中尉", 3]
"客５" = ["客人５", 3]
"ニュースキャスター" = ["新闻播音员", 2]
"おっさん５" = ["大叔５", 2]
"海水浴客５" = ["海水浴客５", 2]
"若い男３" = ["年轻男子３", 2]
"かみさん" = ["老板娘", 2]
"常連客６" = ["常客６", 2]
"店主５" = ["店主５", 2]
"バロン" = ["巴隆", 2]
"店主３" = ["店主３", 2]
"店主１" = ["店主１", 2]
"店主２" = ["店主２", 2]
"親父" = ["老爹", 2]
"肉屋" = ["肉店", 2]
"靴屋" = ["鞋店", 2]
"リサ・まゆ・志乃" = ["莉莎・真由・志乃", 1]
"優しいお隣さん" = ["温柔的邻居", 1]
"リサ・まゆ" = ["莉莎・真由", 1]
"常連客たち" = ["常客们", 1]
"桜子・志乃" = ["樱子・志乃", 1]
"若い客２" = ["年轻客人２", 1]
"若い客１" = ["年轻客人１", 1]
"客１・２" = ["客人１・２", 1]
"通行人１" = ["通行人１", 1]
"タバコ屋" = ["烟草店", 1]
"通行人２" = ["通行人２", 1]
"常連客４" = ["常客４", 1]
"桜子の声" = ["樱子的声音", 1]
"常連客３" = ["常客３", 1]
"バロン？" = ["巴隆？", 1]
"常連客１" = ["常客１", 1]
"志乃の声" = ["志乃的声音", 1]
"夏姫の声" = ["夏姬的声音", 1]
"常連客２" = ["常客２", 1]
"桜子達" = ["樱子她们", 1]
"写真屋" = ["照相馆", 1]
"他の客" = ["其他客人", 1]
"ラジオ" = ["收音机", 1]
"店主４" = ["店主４", 1]
"中尉？" = ["中尉？", 1]
"客６" = ["客人６", 1]
"携帯" = ["手机", 1]
"住人" = ["居民", 1]

