# searchStr 可缩写为 org, replaceStr 可缩写为 rep (译前和译后字典同样适用)

gptDict = [
    # 语义标注---------

    { org = "[title]", rep = "[title]", note = "场景标题标记，请保留，标记的该行文本是整个场景（后续对话）的标题，非角色对话或旁白" },
    { org = "[select]", rep = "[select]", note = "选项文本标记，请保留，标记的该行是玩家可选择的选项条目，非角色对话或旁白，通常出现在分支节点处" },


    # 主要角色---------

    # 樱井恭介
    { org = "恭介", rep = "恭介", note = "人名，男性，全名“樱井恭介”（櫻井 恭介，さくらい きょうすけ），青年，自称大学生，实际在自家咖啡店工作，轻浮，好色，孝顺母亲，樱子的儿子" },
    { org = "櫻井恭介", rep = "樱井恭介", note = "人名全名，男性，即“恭介”" },
    { org = "恭介くん", rep = "恭介君", note = "人名，男性，恭介的称呼" },
    { org = "ニート", rep = "啃老族", note = "人名，男性，恭介的称呼" },
    { org = "小猿", rep = "小猴子", note = "人名，男性，对恭介和一马的称呼" },
    { org = "恭介さん", rep = "恭介先生", note = "人名，男性，恭介的称呼" },


    # 樱井樱子
    { org = "桜子", rep = "樱子", note = "人名，女性，全名“樱井樱子”（櫻井 桜子，さくらい さくらこ），外貌极为年轻（被误认为是恭介的妹妹或姐姐），樱井咖啡厅的老板娘，恭介的母亲，开朗、爱撒娇、有些天然、极度童颜、对儿子有过度亲密倾向" },
    { org = "櫻井桜子", rep = "樱井樱子", note = "人名全名，女性，即“樱子”" },
    { org = "母さん", rep = "妈妈", note = "人名代称，通常是恭介对樱子的称呼" },
    { org = "マスター", rep = "老板", note = "人名代称，通常代指樱子（女性）" },
    { org = "桜子さん", rep = "樱子小姐/樱子阿姨", note = "人名，女性，樱子的称呼" },
    { org = "桜子ちゃん", rep = "小樱子", note = "人名，女性，樱子的称呼" },


    { org = "櫻井", rep = "樱井", note = "人名姓氏，恭介和樱子的姓氏" },
    { org = "櫻井", rep = "樱井", note = "人名姓氏，恭介和樱子的姓氏" },

    # 有濑真由
    { org = "まゆ", rep = "真由", note = "人名，女性，全名“有濑真由”（有瀬 まゆ，ありせ まゆ），中学生，有濑神社的女儿，莉莎的挚友，巫女，黑发，内向、文静、天然、" },
    { org = "有瀬まゆ", rep = "有濑真由", note = "人名全名，女性，即“真由”" },
    { org = "有瀬", rep = "有濑", note = "人名姓氏，真由的姓氏" },
    { org = "まゆちゃん", rep = "小真由", note = "人名，女性，真由的称呼" },


    # 伊藤志乃
    { org = "志乃", rep = "志乃", note = "人名，女性，全名“伊藤志乃”（伊藤 志乃，いとう しの），年轻OL，认真、正经、伊藤社长的秘书兼妻子" },
    { org = "伊藤志乃", rep = "伊藤志乃", note = "人名全名，女性，即“志乃”" },
    { org = "伊藤", rep = "伊藤", note = "人名姓氏，志乃的姓氏，通常也代指志乃的丈夫" },
    { org = "志乃さん", rep = "志乃小姐", note = "人名，女性，志乃的称呼" },
    { org = "しのしの", rep = "志乃志乃", note = "人名，女性，志乃的称呼" },

    # 香月夏姬
    { org = "夏姫", rep = "夏姬", note = "人名，女性，全名“香月夏姬”（香月 夏姫，こうづき なつき），年轻主妇，高虎的妻子，八百屋的女儿，香月青果商店的老板娘，豪爽、强势、有点懒散，对恭介像姐姐" },
    { org = "香月夏姫", rep = "香月夏姬", note = "人名全名，女性，即“夏姬”" },
    { org = "夏姫先輩", rep = "夏姬前辈", note = "人名，女性，夏姬的称呼" },
    { org = "夏姫ちゃん", rep = "小夏姬", note = "人名，女性，夏姬的称呼" },
    { org = "嫁さん", rep = "媳妇", note = "人名，女性，高虎对夏姬的称呼" },

    # 香月高虎
    { org = "高虎", rep = "高虎", note = "人名，男性，全名“香月高虎”（香月 高虎，こうづき たかとら），青年，香月青果商店的老板，夏姫的丈夫，温和、寡言、眯眯眼、勤劳，宠妻" },
    { org = "香月高虎", rep = "香月高虎", note = "人名全名，男性，即“高虎”" },
    { org = "高虎先輩", rep = "高虎前辈", note = "人名，男性，高虎的称呼" },
    { org = "高虎くん", rep = "高虎君", note = "人名，男性，高虎的称呼" },
    { org = "旦那", rep = "当家", note = "人名，男性，高虎的称呼" },
    { org = "若旦那", rep = "小老板", note = "人名，男性，高虎的称呼" },

    { org = "香月", rep = "香月", note = "人名姓氏，夏姬和高虎的姓氏" },

    # 西园寺克蕾亚
    { org = "クレア", rep = "克蕾亚", note = "人名，女性，全名“西园寺克蕾亚”（西園寺 クレア，さいおんじ くれあ），年轻继母/人妻，藤兵卫的后妻，莉莎的亲生母亲，金发巨乳，成熟妩媚、善于诱惑、大胆" },
    { org = "西園寺クレア", rep = "西园寺克蕾亚", note = "人名全名，女性，即“克蕾亚”" },
    { org = "クレアさん", rep = "克蕾亚小姐/克蕾亚阿姨", note = "人名，女性，克蕾亚的称呼" },
    { org = "お母さん", rep = "妈妈", note = "人名代称，通常是莉莎对克蕾亚的称呼" },

    # 西园子莉莎
    { org = "リサ", rep = "莉莎", note = "人名，女性，全名“西园子莉莎”（西園寺 リサ，さいおんじ りさ），中学生，克蕾亚的亲女儿，藤兵卫的继女，真由的挚友，金发，活泼、小恶魔、有点任性，对恭介有好感但傲娇" },
    { org = "西園寺リサ", rep = "西园子莉莎", note = "人名全名，女性，即“莉莎”" },
    { org = "リサちゃん", rep = "小莉莎", note = "人名，女性，莉莎的称呼" },


    { org = "藤兵衛", rep = "藤兵卫", note = "人名，男性，全名“西园寺藤兵卫”（西園寺 藤兵衛），老年（商业街振兴会会长），克蕾亚的后夫，莉莎的继父，温和、开明、振兴商店街热心" },
    { org = "藤兵衛さん", rep = "藤兵卫先生", note = "人名，男性，藤兵卫的称呼" },


    { org = "西園寺", rep = "西园寺", note = "人名姓氏，克蕾亚和莉莎的姓氏" },

    # 二之宫一马
    { org = "一馬", rep = "一马", note = "人名，男性，全名“二之宫一马”（二之宮 一馬，にのみや かずま），自称大学生，轻浮、好色、宅，恭介的损友，电器店相关" },
    { org = "二之宮一馬", rep = "二之宫一马", note = "人名全名，男性，即“一马”" },
    { org = "二之宮", rep = "二之宫", note = "人名姓氏，一马的姓氏" },

    # 田中五十六
    { org = "五十六", rep = "五十六", note = "人名，男性，全名“田中五十六”（田中 五十六，たなか いそろく）" },
    { org = "田中五十六", rep = "田中五十六", note = "人名全名，男性，即“五十六”" },
    { org = "田中", rep = "田中", note = "人名姓氏，五十六和幸子的姓氏" },

    # 田中幸子
    { org = "幸子", rep = "幸子", note = "人名，女性，全名“田中幸子”（田中 幸子，たなか さちこ）" },
    { org = "田中幸子", rep = "田中幸子", note = "人名全名，女性，即“幸子”" },

    # 其他术语/角色---------
    { org = "喫茶サクライ", rep = "樱井咖啡厅", note = "商店名" },
    { org = "コスプレ喫茶", rep = "cosplay咖啡厅", note = "为对抗再开发而想出的经营策略，女性角色穿cos服接客" },


    { org = "サクライ", rep = "樱井", note = "店名" },
    { org = "香月青果商店", rep = "香月蔬果商店", note = "商店名" },
    { org = "有瀬神社", rep = "有濑神社", note = "地名，神社" },
    { org = "オーシャンランド", rep = "海洋乐园", note = "邻站的大型游乐园/度假村" },
    { org = "商店街振興会", rep = "商业街振兴会", note = "本地商店街的组织，藤兵卫是会长" },

    { org = "サイフォン", rep = "虹吸壶", note = "虹吸式咖啡壶，利用虹吸原理冲泡咖啡的玻璃器具" },
    { org = "ネルドリップ", rep = "法兰绒手冲", note = "使用法兰绒滤布而非滤纸的手冲咖啡方式，口感更醇厚" },
    { org = "韓流ドラマ", rep = "韩剧", note = "夏姫的兴趣爱好，沉迷到录下来半夜看" },


    { org = "伊藤社長", rep = "伊藤社长", note = "人名，男性，海洋乐园的社长，志乃的丈夫，中年，轻浮、好色，天然、随性、乐观" },
    { org = "社長", rep = "社长", note = "人名代称，通常代指伊藤社长（男性，志乃的丈夫）" },

    { org = "大輔", rep = "大辅", note = "人名，男性，已故，樱井咖啡厅前老板，樱子的亡夫，恭介的养父" },
    { org = "パパ", rep = "爸爸", note = "人名代称，通常代指大辅，已故，樱井咖啡厅前老板，樱子的亡夫，恭介的养父" },

    { org = "八百屋", rep = "八百屋", note = "地名/店名" },
    { org = "二之宮電器店", rep = "二之宫电器店", note = "一马的家/店" },


    # 其他---------
    { org = "客", rep = "客人", note = "普通名词，指代店内顾客" },
    { org = "客１", rep = "客人１", note = "普通名词，指代店内顾客" },
    { org = "客２", rep = "客人２", note = "普通名词，指代店内顾客" },
    { org = "客１・２", rep = "客人１・２", note = "组合，指代店内顾客" },
    { org = "客３", rep = "客人３", note = "普通名词，指代店内顾客" },
    { org = "客４", rep = "客人４", note = "普通名词，指代店内顾客" },
    { org = "客５", rep = "客人５", note = "普通名词，指代店内顾客" },
    { org = "客６", rep = "客人６", note = "普通名词，指代店内顾客" },
    { org = "海水浴客１", rep = "海水浴客１", note = "角色" },
    { org = "海水浴客２", rep = "海水浴客２", note = "角色" },
    { org = "海水浴客３", rep = "海水浴客３", note = "角色" },
    { org = "海水浴客４", rep = "海水浴客４", note = "角色" },
    { org = "海水浴客５", rep = "海水浴客５", note = "角色" },
    { org = "海水浴客６", rep = "海水浴客６", note = "角色" },
    { org = "若い客１", rep = "年轻客人１", note = "角色" },
    { org = "若い客２", rep = "年轻客人２", note = "角色" },
    { org = "女性客１", rep = "女客１", note = "角色，女性" },
    { org = "女性客２", rep = "女客２", note = "角色，女性" },
    { org = "常連客", rep = "常客", note = "角色" },
    { org = "常連客１", rep = "常客１", note = "角色" },
    { org = "常連客２", rep = "常客２", note = "角色" },
    { org = "常連客３", rep = "常客３", note = "角色" },
    { org = "常連客４", rep = "常客４", note = "角色" },
    { org = "常連客６", rep = "常客６", note = "角色" },
    { org = "常連客たち", rep = "常客们", note = "角色" },
    { org = "みんな", rep = "大家", note = "代词" },
    { org = "全員", rep = "全员", note = "代词，指代文中的全体成员" },
    { org = "おっさん", rep = "大叔", note = "人名（通用代称），男性" },
    { org = "おっさん１", rep = "大叔１", note = "人名（通用代称），男性" },
    { org = "おっさん２", rep = "大叔２", note = "人名（通用代称），男性" },
    { org = "おっさん３", rep = "大叔３", note = "人名（通用代称），男性" },
    { org = "おっさん４", rep = "大叔４", note = "人名（通用代称），男性" },
    { org = "おっさん５", rep = "大叔５", note = "人名（通用代称），男性" },
    { org = "同級生１", rep = "同班同学１", note = "角色" },
    { org = "同級生２", rep = "同班同学２", note = "角色" },
    { org = "同級生３", rep = "同班同学３", note = "角色" },
    { org = "同級生４", rep = "同班同学４", note = "角色" },
    { org = "同級生５", rep = "同班同学５", note = "角色" },
    { org = "志乃の後輩１", rep = "志乃的后辈１", note = "角色" },
    { org = "志乃の後輩２", rep = "志乃的后辈２", note = "角色" },
    { org = "志乃の後輩３", rep = "志乃的后辈３", note = "角色" },
    { org = "志乃の後輩４", rep = "志乃的后辈４", note = "角色" },
    { org = "ナンパ１", rep = "搭讪男１", note = "称呼，男性" },
    { org = "ナンパ２", rep = "搭讪男２", note = "称呼，男性" },
    { org = "ナンパ３", rep = "搭讪男３", note = "角色，男性" },
    { org = "ナンパ４", rep = "搭讪男４", note = "称呼，男性" },
    { org = "小笠原・父", rep = "小笠原・父", note = "人名，男性" },
    { org = "小笠原・母", rep = "小笠原・母", note = "人名，女性" },
    { org = "香月・母", rep = "香月・母", note = "人名，女性" },
    { org = "香月・父", rep = "香月・父", note = "人名，男性" },
    { org = "通行人１", rep = "通行人１", note = "角色" },
    { org = "通行人２", rep = "通行人２", note = "角色" },
    { org = "主婦１", rep = "主妇１", note = "人名，女性" },
    { org = "店主１", rep = "店主１", note = "角色" },
    { org = "店主２", rep = "店主２", note = "角色" },
    { org = "店主３", rep = "店主３", note = "角色" },
    { org = "店主４", rep = "店主４", note = "角色" },
    { org = "店主５", rep = "店主５", note = "角色" },
    { org = "携帯", rep = "手机", note = "物品" },
    { org = "若い男１", rep = "年轻男子１", note = "角色，男性" },
    { org = "若い男２", rep = "年轻男子２", note = "角色，男性" },
    { org = "若い男３", rep = "年轻男子３", note = "角色，男性" },
    { org = "他の客", rep = "其他客人", note = "角色" },

    { org = "桜子達", rep = "樱子她们", note = "组合，女性" },
    { org = "桜子・志乃", rep = "樱子・志乃", note = "组合，女性" },
    { org = "リサ・まゆ・志乃", rep = "莉莎・真由・志乃", note = "组合，女性" },
    { org = "リサ・まゆ", rep = "莉莎・真由", note = "组合，女性" },
    { org = "桜子・夏姫・クレア", rep = "樱子・夏姬・克蕾亚", note = "组合，女性" },

    { org = "男の声", rep = "男人的声音", note = "角色，男性" },
    { org = "桜子の声", rep = "樱子的声音", note = "角色，女性" },
    { org = "夏姫の声", rep = "夏姬的声音", note = "角色，女性" },

    { org = "優しいお隣さん", rep = "温柔的邻居", note = "角色" },
    { org = "ニュースキャスター", rep = "新闻播音员", note = "角色" },
    { org = "老婦人", rep = "老妇人", note = "角色，女性" },
    { org = "？？？", rep = "？？？", note = "未知角色" },
    { org = "老人", rep = "老人", note = "角色，男性" },
    { org = "盗撮男", rep = "偷拍男", note = "人名，男性" },
    { org = "レポーター", rep = "记者", note = "职业称呼" },
    { org = "ディレクター", rep = "导演", note = "职业称呼" },
    { org = "ラジオ", rep = "收音机", note = "物品" },
    { org = "須礼寺浜海岸", rep = "须礼寺滨海岸", note = "地名" },
    { org = "須礼寺浜商店街", rep = "须礼寺滨商店街", note = "地名" },

    { org = "お姉さん", rep = "大姐姐", note = "称呼，女性" },
    { org = "魚辰", rep = "鱼辰", note = "人名，男性" },
    { org = "豆田", rep = "豆田", note = "人名，男性" },
    { org = "親父", rep = "老爹", note = "称呼，男性" },
    { org = "ピョン様", rep = "飘大人", note = "人名，女性" },
    { org = "杉崎", rep = "杉崎", note = "姓氏，志乃的旧姓" },
    { org = "ミキ", rep = "美希", note = "人名，女性" },

    { org = "中尉", rep = "中尉", note = "角色" },
    { org = "中尉？", rep = "中尉？", note = "角色" },
    { org = "写真屋", rep = "照相馆", note = "角色/店名" },
    { org = "部長", rep = "部长", note = "角色" },
    { org = "課長代理", rep = "课长代理", note = "角色" },
    { org = "かみさん", rep = "老板娘", note = "角色，女性" },
    { org = "タバコ屋", rep = "烟草店", note = "角色/店名" },
    { org = "肉屋", rep = "肉店", note = "角色/店名" },
    { org = "靴屋", rep = "鞋店", note = "角色/店名" },
    { org = "豆腐屋", rep = "豆腐店", note = "角色/店名" },
    { org = "バロン", rep = "巴隆", note = "人名，男性" },
    { org = "バロン中尉", rep = "巴隆中尉", note = "角色，男性" },
    { org = "バロン？", rep = "巴隆？", note = "人名，男性" },
    { org = "イトウリゾート", rep = "伊藤度假村", note = "组织/地点名" },
    { org = "メグミ", rep = "惠", note = "人名，女性" },
    { org = "瓜原", rep = "瓜原", note = "人名，男性" },

]
